config/routes.rb
Blog::Application.routes.draw do


		 	get "/tododb/" => "todo#todo"

			get "/display/:id" => "todo#find"

		 	get "done/:id" => "todo#done"	
		 	get "prorogue/:id" => "todo#prorogue"
		 	get "delete/:id" => "todo#delete"

			post "created/"=> "todo#created"
			get "new/"=>"todo#new"
			
 			post "summ/" => "summ#count"
			get "summ/summ" => "summ#summ"

	end		

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :todo
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  has_many :comments
end

app/controllers/E100_E50/E100_E50.rb
class E100_E50 < ApplicationController
	def E100
	end
  def E50
  end 	
end

app/controllers/GW_P_Jagedtiger/GW_P_Jagedtiger.rb
class GW_P_Jagedtiger < ApplicationController
	def Jagedtiger 
	end
  def GW_P
  end 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @todo = Todo.find(params[:id])
    @comment = comments.create(params[:comment])
    redirect_to todo_path(@todo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
  	def dima
  	end 	
  	def alina
  	end
  	def kot
  	end
end

app/controllers/home_controller/home_controller.rb
class HomeController < ApplicationController
	def index
	end
  def hello
  end 	
end

app/controllers/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title
 
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
 
  has_many :comments
end

app/controllers/postname_controller.rb
class postsummController < ApplicationController
  	def 
  
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end


  end
end

app/controllers/random_T-50-2/random_T-50-2.rb
class random_T-50-2 < ApplicationController
	def random
	end
  def T-50-2
  end 	
end

app/controllers/real_wtf_S-51/real_wtf_S-51.rb
class real_wtf_S-51 < ApplicationController
	def real_wtf
	end
  def S-51
  end 	
end

app/controllers/sayhello_controller.rb
class SayhelloController < ApplicationController
  	def display
  @say_to = params['who']
end
end

app/controllers/some_name_T92/some_name_T92.rb
class some_name_T92 < ApplicationController
	def some_name 
	end
  def T92
  end 	
end

app/controllers/summ_controller.rb
class SummController < ApplicationController
	def count	
  if params["GROUP"] == "Plus"
		  @calc = params['ras'].to_i + params['dva'].to_i
		elsif params["GROUP"] == "Minus"
		  	@calc = params['ras'].to_i - params['dva'].to_i
		  	elsif params["GROUP"] == "Multiplication"
		  		@calc = params['ras'].to_i * params['dva'].to_i
		  		elsif params["GROUP"] == "Division"
		  			@calc = params['ras'].to_f / params['dva'].to_f
		  			

		  			end

						end
	def summ
end

end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
	def todo
		@todo = Todo.all
	end
	def find
			@todo = Todo.find(params['id'])
	end
	def done
		@todo = Todo.find(params['id'])
			@todo.update_attributes(:status => '2')
			if @todo.save
			else
				flash[:error] = "Could not update todo"
			end
			redirect_to tododb_path
			
	end
	def prorogue
		@todo = Todo.find(params['id'])
			@todo.update_attributes(:status => '3')
			if @todo.save
			else
				flash[:error] = "Could not find todo"
			end
			redirect_to tododb_path
	end
	def delete
		@todo = Todo.find(params['id'])	
			if @todo == nil	
				flash[:error] = "Could not find todo"					
			else
				flash[:notice] = "deleted successfully"
			end
			@todo.destroy
			redirect_to tododb_path				
	end 
	def new
		end
	def created
		@todo = Todo.create(:name => params['NewTodo'], :status => "1")
		if @todo.save
			else
				flash[:error] = "Could not create todo"
			end
			redirect_to tododb_path
	end
		def show
		end
end

app/controllers/trouble_wtf/trouble_wtf.rb
class trouble_wtf < ApplicationController
	def trouble
	end
  def wtf
  end 	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/todo/find.html.erb
<h1><%=@todo.id%>|<%=@todo.name%>|<%=@todo.status%></h1>

app/views/todo/new.html.erb
<form name="NewTodo" action="/created" method="POST"> 
<input name="NewTodo" type="text" />New Todo 
<input type="submit" value="Save" />

</form>

app/views/todo/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>
 
<h2>Comments</h2>
<% @todo.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@todo, @todo.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit Comment', edit_todo_path(@todo) %>

app/views/todo/todo.html.erb
<html>
<head>
	<center><h3>My todo list </h3></center>
  <p><% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
     <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>
  </p>
</head>
<body>
<% @todo.each do |todo| %>

		     <p>
          ID :<%=todo.id %>
          
          <p>
  		
  			<p>status:<%=todo.status%></p>
  		
		    <p>task:<%=todo.name %></p>
       <br>
</table>
<% end %>

</body>




<footer>1 - не сделанно, 2 - сделанно, 3 - отложенно</footer>
</html>